<?php

return [

    'par1'=> "Benvingut a  My Green Partner, una aplicació web basada en el framework Laravel, conegut per la seva elegància, robustesa i facilitat d'ús. Ens vam proposar el desafiament de crear una plataforma web que combini a la manipulació de bases de dades amb la nostra passió per les plantes. El nostre objectiu principal és aprendre i dominar les habilitats tècniques necessàries per a gestionar eficientment una base de dades a través d'una aplicació web. En  My Green Partner, utilitzem el patró Model-Vista-Controlador (MVC) proporcionat per Laravel per a estructurar la nostra aplicació. Això ens permet separar la lògica de negoci (model), la presentació de dades (vista) i la interacció de l'usuari (controlador), la qual cosa facilita el manteniment i l'escalabilitat de la plataforma.",
    'par2'=> "La base de dades de  My Green Partner està dissenyada amb múltiples taules que es relacionen entre si. En l'apartat 'Troba la teva planta perfecta', fem ús d'una relació 'many to many' per a relacionar les plantes amb els tipus de llum solar. Aquesta relació ens permet accedir a múltiples opcions de llum solar associats a cada planta, la qual cosa t'ajuda a trobar les plantes adequades segons les teves necessitats i l'entorn en el qual les col·locaràs. Per a enriquir la nostra base de dades, recopilem informació de fonts externes a través d'una API d'Internet (https://www.perenual.com/docs/api) i també agreguem dades manualment segons les sol·licituds dels usuaris. Això ens permet mantenir una àmplia varietat de plantes i assegurar que la informació sigui precisa i actualitzada. A més,  My Green Partner fa ús de les funcionalitats de traducció proporcionades per Laravel. Actualment, la plataforma està disponible en català, i estem treballant per a expandir la seva disponibilitat a altres idiomes, com l'anglès, que és l'idioma predominant amb el qual hem treballat. Valorem la importància d'oferir una experiència multilingüe per als nostres usuaris i ens esforcem per garantir que tots puguin gaudir de  My Green Partner sense barreres lingüístiques.",
    'par3'=>"En l'apartat de la comunitat, utilitzem taules de relació 'one to many' per a gestionar les preguntes i respostes. Els usuaris poden realitzar preguntes i altres membres de la comunitat poden respondre i participar en les discussions. A més, hem implementat un sistema d'autenticació i autorització per a garantir la integritat de les interaccions i proporcionar un entorn segur. Hem pres mesures per a protegir la informació dels usuaris, les contrasenyes s'emmagatzemen de forma encriptada en la nostra base de dades, la qual cosa garanteix la confidencialitat de les dades personals. En quant a la seguretat, seguim bones pràctiques per a evitar possibles vulnerabilitats i protegir la integritat de la nostra plataforma.",
    'par4'=>"Aquesta aplicació és part del projecte de final de grau del Grau d'Enginyeria de Telecomunicacions impartit per la UOC, en què hem posat en pràctica els coneixements adquirits al llarg de la nostra formació. Mitjançant una exhaustiva investigació i desenvolupament, hem treballat per a oferir-te una plataforma robusta i de qualitat. Valorem la teva participació i t'animem a unir-te a la nostra comunitat, compartir els teus coneixements i experiències, i col·laborar en el creixement continu de la nostra plataforma. En  My Green Partner, la seguretat i el manteniment de la base de dades són aspectes fonamentals per a garantir un funcionament correcte i de confiança. Estem compromesos amb proporcionar un entorn segur i de confiança per a tots els usuaris.",
    'par5'=>"Et convidem a explorar cada secció de la nostra pàgina web, aprofitar les funcionalitats que oferim i unir-te a la nostra comunitat d'entusiastes de les plantes. Esperem veure't aviat en  My Green Partner i compartir junts l'apassionant món de les plantes!",
];